language: node_js
node_js:
  - "8"
addon:
  chrome: stable
sudo: required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chomd root /opt/google/chrome/chrome-sandbox"